// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import FieldsController from "./fields_controller";
application.register("fields", FieldsController);

import FlashController from "./flash_controller";
application.register("flash", FlashController);

import CourseLessonsController from "./course_lessons_controller";
application.register("course-lessons", CourseLessonsController);

import DetailsController from "./details_controller";
application.register("details", DetailsController);

import DialogController from "./dialog_controller";
application.register("dialog", DialogController);

import NavController from "./nav_controller";
application.register("nav", NavController);

import PrintController from "./print_controller";
application.register("print", PrintController);

import ScrollToController from "./scroll_to_controller";
application.register("scroll-to", ScrollToController);

import TestResultController from "./test_result_controller";
application.register("test-result", TestResultController);

import ThemeController from "./theme_controller";
application.register("theme", ThemeController);

import UploadSummaryController from "./uploaders/upload_summary_controller";
application.register("upload-summary", UploadSummaryController);

import ParentUploaderController from "./uploaders/parent_uploader/parent_uploader_controller";
application.register("parent-uploader", ParentUploaderController);

import StudentUploaderController from "./uploaders/student_uploader/student_uploader_controller";
application.register("student-uploader", StudentUploaderController);

import TeacherUploaderController from "./uploaders/teacher_uploader/teacher_uploader_controller";
application.register("teacher-uploader", TeacherUploaderController);

import ValidityController from "./validity_controller";
application.register("validity", ValidityController);

import TurboModalController from "./turbo_modal_controller";
application.register("turbo-modal", TurboModalController);
