// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FieldsController from "./fields_controller"
application.register("fields", FieldsController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import NavRevealController from "./nav_reveal_controller"
application.register("nav-reveal", NavRevealController)

import PrintController from "./print_controller"
application.register("print", PrintController)

import ScrollToController from "./scroll_to_controller"
application.register("scroll-to", ScrollToController)

import TestResultController from "./test_result_controller"
application.register("test-result", TestResultController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import TurboModalController from "./turbo_modal_controller"
application.register("turbo-modal", TurboModalController)

import Uploaders__ParentUploader__ParentUploaderController from "./uploaders/parent_uploader/parent_uploader_controller"
application.register("uploaders--parent-uploader--parent-uploader", Uploaders__ParentUploader__ParentUploaderController)

import Uploaders__StudentUploader__StudentUploaderController from "./uploaders/student_uploader/student_uploader_controller"
application.register("uploaders--student-uploader--student-uploader", Uploaders__StudentUploader__StudentUploaderController)

import Uploaders__TeacherUploader__TeacherUploaderController from "./uploaders/teacher_uploader/teacher_uploader_controller"
application.register("uploaders--teacher-uploader--teacher-uploader", Uploaders__TeacherUploader__TeacherUploaderController)

import Uploaders__UploadSummaryController from "./uploaders/upload_summary_controller"
application.register("uploaders--upload-summary", Uploaders__UploadSummaryController)

import ValidityController from "./validity_controller"
application.register("validity", ValidityController)
