version: "3"

services:
  web:
    environment:
      - PUPPETEER_DISABLE_SHUTDOWN_HANDLERS=1
    platform: linux/amd64
    build: .
    ports:
      - "80:80"
    volumes:
      - ./app:/rails/app
    env_file:
      - .env/development/database
      - .env/development/web
    deploy:
      resources:
        limits:
          memory: 1G

  database:
    platform: linux/amd64
    image: postgres
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
