# frozen_string_literal: true

require 'rails_helper'

RSpec.describe Student do
  it 'has a valid factory' do
    expect(build(:student)).to be_valid
  end

  it 'cannot have duplicate student IDs at same school' do
    student = create(:student, student_id: '123')
    duplicate = build(:student, student_id: '123', school: student.school)
    expect(duplicate).not_to be_valid
  end

  it 'can have duplicate student IDs at different schools' do
    create(:student, student_id: '123')
    duplicate = build(:student, student_id: '123', school: create(:school))
    expect(duplicate).to be_valid
  end

  it 'autogenerates student ID from DB id, school_id if not set' do
    school = create(:school)
    student = create(:student, school:, student_id: nil)
    expect(student.reload.student_id).to include("#{student.id}-#{school.id}-")
  end

  it 'can reassign student ID that was autogenerated' do
    student = create(:student, student_id: nil)
    student.update(student_id: '123')
    expect(student.reload.student_id).to eq('123')
  end
end
