default: &default
  dispatchers:
    - polling_interval: 2
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      processes: 1
      polling_interval: 1
      terminate_when_idle: false

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
